import { useState } from "react";
import styles from "./Hero.module.css";

/**
 * Vela waitlist hero — shipped from Figma node `373:8840`.
 *
 * Fidelity notes, so the next person does not have to re-derive them:
 * - Every color is a `var(--token)` from `tokens.css`, generated by
 *   `figma-cli export dtcg` + `scripts/dtcg-to-css.js`. Never `export css` — it
 *   emits `#NaNNaNNaN` for every aliased semantic token.
 * - Type is Outfit throughout, identified by rendering a specimen and comparing
 *   glyphs against the reference, not guessed. 34/46 display, 17/25 body.
 * - Icons are inline SVG. The reference's sparkle and 3-line burger are absent
 *   from the pinned Iconsax twotone set, and `TASTE.md` forbids substituting a
 *   different variant — so they are drawn in the set's own language.
 */

type HeroProps = {
  /** Rendered as the eyebrow pill. Omit to hide it. */
  eyebrow?: string;
  headline?: readonly [string, string];
  subcopy?: string;
  ctaLabel?: string;
  microcopy?: string;
  proof?: { initials: readonly string[]; text: string };
  onJoin?: () => void | Promise<void>;
};

const DEFAULTS = {
  eyebrow: "Now accepting early access",
  headline: ["Your work,", "finally in flow."] as const,
  subcopy:
    "Vela is the AI workspace that removes friction between your thoughts and your output. Built for founders who move fast.",
  ctaLabel: "Join the waitlist",
  microcopy: "No credit card. No noise. Just early access.",
  proof: { initials: ["AK", "MJ", "RS"] as const, text: "2,847 founders already on the list" },
};

/** Filled 4-point sparkle. `aria-hidden` — the eyebrow text carries the meaning. */
function Sparkle() {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
      <path d="M12 1.5s1.05 6.6 2.4 7.95S22.5 12 22.5 12s-6.75 1.2-8.1 2.55S12 22.5 12 22.5s-1.05-6.6-2.4-7.95S1.5 12 1.5 12s6.75-1.2 8.1-2.55S12 1.5 12 1.5Z" />
    </svg>
  );
}

/** Iconsax-twotone 3-line menu: full-opacity middle rule, 0.4 outer rules. */
function MenuIcon() {
  return (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path d="M3 5h18" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" opacity="0.4" />
      <path d="M3 12h18" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" />
      <path d="M3 19h18" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" opacity="0.4" />
    </svg>
  );
}

function Logo() {
  return (
    <svg viewBox="0 0 30 30" fill="none" aria-hidden="true">
      <path d="M4 6l11 18L26 6h-5.5L15 15.5 9.5 6H4Z" fill="var(--accent)" />
    </svg>
  );
}

export function Hero({
  eyebrow = DEFAULTS.eyebrow,
  headline = DEFAULTS.headline,
  subcopy = DEFAULTS.subcopy,
  ctaLabel = DEFAULTS.ctaLabel,
  microcopy = DEFAULTS.microcopy,
  proof = DEFAULTS.proof,
  onJoin,
}: HeroProps) {
  const [state, setState] = useState<"idle" | "loading" | "done" | "error">("idle");

  async function handleJoin() {
    if (state === "loading" || state === "done") return;
    setState("loading");
    try {
      await onJoin?.();
      setState("done");
    } catch {
      setState("error");
    }
  }

  // Copy keeps the action's name through the whole flow, per states.md: "Join the
  // waitlist" becomes "You're on the list", never "Success".
  const label =
    state === "loading" ? "Joining…" : state === "done" ? "You're on the list" : ctaLabel;

  return (
    <section className={styles.hero}>
      <header className={styles.nav}>
        <span className={styles.logo}>
          <Logo />
        </span>

        <div className={styles.navRight}>
          <nav className={styles.navLinks} aria-label="Primary">
            <a href="#product">Product</a>
            <a href="#pricing">Pricing</a>
            <a href="#about">About</a>
          </nav>

          <button type="button" className={styles.navPill} onClick={handleJoin}>
            {ctaLabel}
          </button>

          <button type="button" className={styles.menuButton} aria-label="Open menu">
            <MenuIcon />
          </button>
        </div>
      </header>

      <div className={styles.content}>
        {eyebrow && (
          <p className={`${styles.eyebrow} ${styles.reveal}`}>
            <Sparkle />
            {eyebrow}
          </p>
        )}

        {/* The line break is load-bearing — it is the signature element in TASTE.md.
            A <br> preserves it at every width rather than leaving it to wrapping. */}
        <h1 className={`${styles.headline} ${styles.reveal}`}>
          {headline[0]}
          <br />
          {headline[1]}
        </h1>

        <p className={`${styles.subcopy} ${styles.reveal}`}>{subcopy}</p>

        <button
          type="button"
          className={`${styles.cta} ${styles.reveal}`}
          onClick={handleJoin}
          disabled={state === "loading" || state === "done"}
          aria-live="polite"
        >
          {label}
        </button>

        <p className={`${styles.microcopy} ${styles.reveal}`} role={state === "error" ? "alert" : undefined}>
          {state === "error"
            ? "That didn't go through. Check your connection and try again."
            : microcopy}
        </p>

        <div className={styles.proof}>
          {/* Decorative: the count in proofText already states the meaning. */}
          <div className={styles.avatars} aria-hidden="true">
            {proof.initials.map((initials) => (
              <span key={initials} className={styles.avatar}>
                {initials}
              </span>
            ))}
          </div>
          <p className={styles.proofText}>{proof.text}</p>
        </div>
      </div>
    </section>
  );
}

export default Hero;
