#!/usr/bin/env node
/* Build CSS custom properties from a DTCG export.
 *
 * Why this exists: `figma-cli export css` cannot resolve variable aliases and emits
 * `--accent: #NaNNaNNaN;` for every semantic token — verified across all 21 semantic
 * tokens in a real file. `figma-cli export dtcg` keeps the aliases as `{blue.500}`
 * references, which is strictly more information: this converts each one to a
 * `var(--blue-500)` reference, so the indirection survives into CSS and a theme
 * switch still works.
 *
 * Usage: node scripts/dtcg-to-css.js tokens.json [> tokens.css]
 */
const fs = require("fs");

const file = process.argv[2];
if (!file) {
  console.error("usage: node dtcg-to-css.js <tokens.json>");
  process.exit(1);
}
const tokens = JSON.parse(fs.readFileSync(file, "utf8"));

const flatten = (obj, path = []) => {
  const out = [];
  for (const [k, v] of Object.entries(obj)) {
    if (v && v.$value !== undefined) out.push([[...path, k].join("-"), v.$value, v.$type]);
    else if (v && typeof v === "object") out.push(...flatten(v, [...path, k]));
  }
  return out;
};

// {blue.500} -> var(--blue-500). A DTCG alias is dot-separated; CSS names are hyphenated.
const toCss = (value) => {
  if (typeof value !== "string") return value;
  const m = value.match(/^\{(.+)\}$/);
  return m ? "var(--" + m[1].replace(/\./g, "-") + ")" : value;
};

const rows = flatten(tokens);
const primitives = rows.filter(([, v]) => typeof v !== "string" || !v.startsWith("{"));
const aliases = rows.filter(([, v]) => typeof v === "string" && v.startsWith("{"));

const lines = [
  "/* Generated by scripts/dtcg-to-css.js from a figma-cli DTCG export.",
  " * Do not hand-edit: regenerate with",
  " *   figma-cli export dtcg tokens.json && node scripts/dtcg-to-css.js tokens.json",
  " * `figma-cli export css` is NOT a substitute — it emits #NaNNaNNaN for every alias.",
  " */",
  ":root {",
  "  /* primitives */",
  ...primitives.map(([k, v]) => "  --" + k + ": " + v + ";"),
  "",
  "  /* semantic — alias references preserved, so theming still works */",
  ...aliases.map(([k, v]) => "  --" + k + ": " + toCss(v) + ";"),
  "}",
];

process.stdout.write(lines.join("\n") + "\n");
process.stderr.write(
  "wrote " + primitives.length + " primitive(s) and " + aliases.length + " alias(es)\n"
);
